public enum FieldSoil : byte
{
    Acrisols = 0,
    Albeluvisols = 1,
    Alisols = 2,
    Andosols = 3,
    Arenosols = 4,
    Calcisols = 5,
    Cambisols = 6,
    Chernozems = 7,
    Cryosols = 8,
    Durisols = 9,
    Ferralsols = 10,
    Fluvisols = 11,
    Gleysols = 12,
    Gypsisols = 13,
    Histosols = 14,
    Kastanozems = 15,
    Leptosols = 16,
    Lixisols = 17,
    Luvisols = 18,
    Nitisols = 19,
    Phaeozems = 20,
    Planosols = 21,
    Plinthosols = 22,
    Podzols = 23,
    Regosols = 24,
    Solonchaks = 25,
    Solonetz = 26,
    Stagnosols = 27,
    Umbrisols = 28,
    Vertisols = 29,

    None = 255,
}